# Generated by Django 4.2 on 2023-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Baby', 'Baby'), ('Women', 'Women'), ('Men', 'Men')], max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='latest_post_images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Baby', 'Baby'), ('Women', 'Women'), ('Men', 'Men')], max_length=100),
        ),
    ]
